CREATE USER 'maxwell'@'%' IDENTIFIED BY 'maxwell';
GRANT SELECT, REPLICATION CLIENT, REPLICATION SLAVE ON *.* TO 'maxwell'@'%';
CREATE DATABASE maxwell;
GRANT ALL ON maxwell.* TO 'maxwell'@'%';
FLUSH PRIVILEGES;