version: "3.8"
services:

  mysql:
    image: mysql:5.7.34
    platform: linux/amd64
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: "US/Eastern"
    command: "--server-id=1"
    volumes:
      - ./mysql_init/:/docker-entrypoint-initdb.d/
      - ./config/mysql.my.cnf:/etc/my.cnf
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - mysql

networks:
  mysql:
    name: mysql
